name: Deploy

on:
    push:
        branches:
            - prod

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v2
            - name: ssh and deploy
              uses: appleboy/ssh-action@master
              env:
                  HOST: ${{ secrets.HOST }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PORT: ${{ secrets.PORT }}
                  KEY: ${{ secrets.SSHKEY }}

              with:
                  source: '.'
                  target: '~/Bots/ApexStats'
